services:
  db:
    image: postgres:15.3
    container_name: database
    restart: always
    ports:
      - 5432:5432
    networks:
      - local-net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: local_db
    volumes:
      - db:/var/lib/postgresql

networks:
  local-net:
    driver: bridge

volumes:
    db: