spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/local_db
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    show-sql: false
